version: 2.1

.journey: &journey
  steps:
  - checkout
  - run:
      name: run the tests
      command: ./bin/journey-test.sh

jobs:
  journey22:
    docker:
    - image: circleci/erlang:22.0.4
    <<: *journey
  journey21:
    docker:
    - image: circleci/erlang:21.3.8.4
    <<: *journey
  journey20:
    docker:
    - image: circleci/erlang:20.3.8.22
    <<: *journey

  configlet:
    docker:
    - image: debian:latest
    steps:
    - checkout
    - run:
        name: check track config
        command: ./bin/fetch-configlet && ./bin/configlet lint .

workflows:
  version: 2
  test:
    jobs:
    - configlet
    - journey22:
        requires: ["configlet"]
    - journey21:
        requires: ["configlet"]
    - journey20:
        requires: ["configlet"]