name: Exercism Erlang Track verification

on: [push, pull_request]

jobs:
  test_erlang:
    name: Test examples against OTP ${{ matrix.otp }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["20.3", "21.3", "22.0"]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
    - name: Install dependencies
      run: apt update && apt install --yes jq
    - name: run tests
      run: ./bin/run_ci.sh
