name: Exercism Erlang Track verification

on: [push, pull_request]

jobs:
  test_erlang:
    name: Test examples against OTP ${{ matrix.otp }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ["22.3", "23.3", "24.1"]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
    - name: Install dependencies
      run: apt update && apt install --yes jq
    - name: run tests
      run: ./bin/run_ci.sh
