name: Check UUID validity

on: [push, pull_request]

jobs:
  uuid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - run: sudo apt install --yes jq
    - run: |
        bad_uuid=$(cat config.json | jq --raw-output '.exercises | map(.uuid) | .[]' | grep -vE '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' || true)
        if [[ -n "$bad_uuid" ]]; then
          printf "Invalid UUID(s) found:"
          printf "%s" "${bad_uuid}"
          exit 1
        fi
